import pygame  # загружаю нужные библиотеки
import sys
import os


def load_image(name, colorkey=None):  # класс для загрузки изображения
    fullname = os.path.join('data', name)
    # если файл не существует, то выходим
    if not os.path.isfile(fullname):
        print(f"Файл с изображением '{fullname}' не найден")
        sys.exit()
    image2 = pygame.image.load(fullname)
    return image2



grass_night = load_image("grass_night.png")
empty = load_image("empty.png")
num = load_image("empty2.png")
junk_can = load_image("junk_can.png")
tree = load_image("tree.png")
leather_stuff = load_image('leatherstuff.png')
stone = load_image('stone.png')
grass_night2 = load_image("grass_night2.png")
sign = load_image('Signs.png')



pol = [empty, grass_night, grass_night2]
barriers = [leather_stuff, tree, junk_can, num, stone, sign]
world = [[grass_night, [stone, grass_night2], grass_night, grass_night2, [stone, grass_night], grass_night2, grass_night, grass_night2, grass_night2, [sign, grass_night], [junk_can, grass_night2], grass_night, [stone, grass_night2], grass_night2, [stone, grass_night], grass_night, grass_night, grass_night2, grass_night2, grass_night, [stone, grass_night], grass_night2, grass_night, [sign, grass_night2], grass_night, grass_night2, grass_night, grass_night2, grass_night, grass_night, grass_night, grass_night2, [junk_can, grass_night], grass_night, [junk_can, grass_night2], grass_night, grass_night, [junk_can, grass_night], grass_night, [stone, grass_night], grass_night2, grass_night, [stone, grass_night], grass_night, [junk_can, grass_night2], grass_night, grass_night, grass_night2],
         [grass_night2, grass_night, grass_night2, grass_night2, grass_night, grass_night2, grass_night, [stone, grass_night], grass_night, grass_night, grass_night2, grass_night2, grass_night, [sign, grass_night], grass_night2, grass_night2, grass_night, [stone, grass_night], grass_night, grass_night, grass_night2, grass_night2, grass_night, grass_night2, grass_night, grass_night, grass_night2, [sign, grass_night], grass_night2, [tree, grass_night], grass_night2, [tree, grass_night], grass_night2, [tree, grass_night], grass_night2, grass_night2, grass_night2, [stone, grass_night], grass_night2, grass_night, grass_night, [junk_can, grass_night2], grass_night, grass_night2, [junk_can, grass_night], grass_night, [stone, grass_night2], grass_night, grass_night, [junk_can, grass_night], grass_night, [junk_can, grass_night], grass_night, grass_night, grass_night, [junk_can, grass_night], grass_night, [sign, grass_night2], grass_night, grass_night ,grass_night, [junk_can, grass_night], grass_night, [junk_can, grass_night2], grass_night, grass_night],
         [[stone, grass_night], grass_night2, grass_night2, [stone, grass_night], grass_night, grass_night2, grass_night, grass_night2, grass_night2, [sign, grass_night], grass_night2, grass_night2, grass_night, [sign, grass_night], grass_night, grass_night2, grass_night2, grass_night, grass_night2, grass_night2, [stone, grass_night], grass_night, grass_night2, grass_night, grass_night, grass_night2, grass_night, grass_night2, grass_night2, grass_night2, grass_night2, grass_night, [stone, grass_night], grass_night2, [stone, grass_night], grass_night, grass_night2, grass_night, grass_night, [junk_can, grass_night2], grass_night, grass_night2, [junk_can, grass_night], grass_night, [stone, grass_night2], grass_night, grass_night, [junk_can, grass_night], grass_night, [junk_can, grass_night2], grass_night, grass_night, grass_night, [junk_can, grass_night], grass_night, [sign, grass_night2], grass_night, grass_night ,grass_night, [junk_can, grass_night], grass_night, [junk_can, grass_night2], grass_night, grass_night],
         [grass_night, grass_night2, grass_night2, grass_night2, grass_night, grass_night2, grass_night, [stone, grass_night], grass_night, grass_night, grass_night2, grass_night2, grass_night, [sign, grass_night], grass_night2, grass_night2, grass_night, [stone, grass_night], grass_night, grass_night, grass_night2, grass_night2, grass_night, grass_night2, grass_night, grass_night, grass_night2, [sign, grass_night], grass_night2, [tree, grass_night], grass_night2, [tree, grass_night], grass_night2, [tree, grass_night], grass_night2, grass_night2, grass_night2, [stone, grass_night], grass_night2, grass_night, grass_night, [junk_can, grass_night2], grass_night, grass_night2, [junk_can, grass_night], grass_night, [stone, grass_night2], grass_night, grass_night, [junk_can, grass_night], grass_night, [junk_can, grass_night2], grass_night, grass_night, grass_night, [junk_can, grass_night], grass_night, [sign, grass_night], grass_night, grass_night ,grass_night, [junk_can, grass_night], grass_night, [junk_can, grass_night2], grass_night, grass_night],
         [[stone, grass_night], grass_night, grass_night2, grass_night2, grass_night, grass_night2, grass_night, [stone, grass_night], grass_night, grass_night, grass_night2, grass_night2, grass_night, [sign, grass_night], grass_night2, grass_night2, grass_night, [stone, grass_night], grass_night, grass_night, grass_night2, grass_night2, grass_night, grass_night2, grass_night, grass_night, grass_night2, [sign, grass_night], grass_night2, [tree, grass_night], grass_night2, [tree, grass_night], grass_night2, [tree, grass_night], grass_night2, grass_night2, grass_night2, [stone, grass_night], grass_night2, grass_night, grass_night, [junk_can, grass_night2], grass_night, grass_night2, [junk_can, grass_night], grass_night, [stone, grass_night2], grass_night, grass_night, [junk_can, grass_night], grass_night, [junk_can, grass_night2], grass_night, grass_night, grass_night, grass_night, grass_night, grass_night2, grass_night, grass_night ,grass_night, grass_night2, grass_night, grass_night, grass_night, grass_night],
         [grass_night, grass_night2, grass_night, grass_night2, grass_night2, grass_night2, grass_night, grass_night, grass_night, grass_night, grass_night2, grass_night2, grass_night, grass_night2, grass_night2, grass_night2, grass_night2, grass_night2, grass_night, grass_night2, grass_night2, grass_night2, grass_night, grass_night2, grass_night, grass_night2, grass_night2, grass_night, grass_night2, grass_night2, grass_night2, grass_night, grass_night2, grass_night2, grass_night2, grass_night2, grass_night, grass_night2, grass_night2, grass_night, grass_night, grass_night2, grass_night, grass_night2, grass_night, grass_night, grass_night, grass_night, grass_night2, grass_night2, grass_night, grass_night, grass_night, grass_night, grass_night, grass_night2, grass_night, grass_night2, grass_night, grass_night ,grass_night, grass_night, grass_night, grass_night, grass_night, grass_night],
         [grass_night, grass_night2, grass_night, grass_night2, grass_night2, grass_night2, grass_night, grass_night, grass_night, grass_night, grass_night2, grass_night2, grass_night, grass_night2, grass_night2, grass_night2, grass_night2, grass_night2, grass_night, grass_night2, grass_night2, grass_night2, grass_night, grass_night2, grass_night, grass_night2, grass_night2, grass_night, grass_night2, grass_night2, grass_night2, grass_night, grass_night2, grass_night2, grass_night2, grass_night2, grass_night, grass_night2, grass_night2, grass_night, grass_night, grass_night2, grass_night, grass_night2, grass_night, grass_night, grass_night, grass_night, grass_night2, grass_night2, grass_night, grass_night, grass_night, grass_night, grass_night, grass_night2, grass_night, grass_night2, grass_night, grass_night ,grass_night, grass_night, grass_night, grass_night, grass_night, grass_night],
         [[stone, grass_night], grass_night, grass_night2, grass_night2, grass_night, grass_night2, grass_night, [stone, grass_night], grass_night, grass_night, grass_night2, grass_night2, grass_night, [sign, grass_night], grass_night2, grass_night2, grass_night, [stone, grass_night], grass_night, grass_night, grass_night2, grass_night2, grass_night, grass_night2, grass_night, grass_night, grass_night2, [sign, grass_night], grass_night2, [tree, grass_night], grass_night2, [tree, grass_night], grass_night2, [tree, grass_night], grass_night2, grass_night2, grass_night2, [stone, grass_night], grass_night2, grass_night, grass_night, [junk_can, grass_night2], grass_night, grass_night2, [stone, grass_night], grass_night2, [stone, grass_night2], grass_night, grass_night, [junk_can, grass_night], [sign, grass_night], [junk_can, grass_night2], grass_night, grass_night, grass_night, [junk_can, grass_night], grass_night, [sign, grass_night], grass_night, grass_night ,grass_night, [junk_can, grass_night], grass_night, [junk_can, grass_night2], grass_night, grass_night],
         [grass_night, grass_night, grass_night2, grass_night2, grass_night, grass_night2, grass_night, [stone, grass_night], grass_night, grass_night, grass_night2, grass_night2, grass_night, [sign, grass_night], grass_night2, grass_night2, grass_night, [stone, grass_night], grass_night, grass_night, grass_night2, grass_night2, grass_night, grass_night2, grass_night, grass_night, grass_night2, [sign, grass_night], grass_night2, [tree, grass_night], grass_night2, [tree, grass_night], grass_night2, [tree, grass_night], grass_night2, grass_night2, grass_night2, [stone, grass_night], grass_night2, grass_night, grass_night, [junk_can, grass_night2], grass_night, grass_night2, grass_night, grass_night, [stone, grass_night2], grass_night, grass_night, [junk_can, grass_night], grass_night, grass_night2, grass_night2, grass_night, grass_night, [junk_can, grass_night], grass_night, [sign, grass_night], grass_night, grass_night ,grass_night, [junk_can, grass_night], grass_night, [junk_can, grass_night2], grass_night, grass_night],
         [[sign, grass_night], grass_night, grass_night2, grass_night2, grass_night, grass_night2, grass_night, [stone, grass_night], grass_night, grass_night, grass_night2, grass_night2, grass_night, [sign, grass_night], grass_night2, grass_night2, grass_night, [stone, grass_night], grass_night, grass_night, grass_night2, grass_night2, grass_night, grass_night2, grass_night, grass_night, grass_night2, [sign, grass_night], grass_night2, [tree, grass_night], grass_night2, [tree, grass_night], grass_night2, [tree, grass_night], grass_night2, grass_night2, grass_night2, [stone, grass_night], grass_night2, grass_night, grass_night, [junk_can, grass_night2], grass_night, grass_night2, grass_night, grass_night, [stone, grass_night2], grass_night, grass_night, [junk_can, grass_night], grass_night, grass_night2, grass_night, grass_night, grass_night, [junk_can, grass_night], grass_night, [sign, grass_night], grass_night, grass_night ,grass_night, [junk_can, grass_night], grass_night, [junk_can, grass_night2], grass_night, grass_night],
         [grass_night, grass_night, grass_night2, grass_night2, grass_night, grass_night2, grass_night, [stone, grass_night], grass_night, grass_night, grass_night2, grass_night2, grass_night, [sign, grass_night], grass_night2, grass_night2, grass_night, [stone, grass_night], grass_night, grass_night, grass_night2, grass_night2, grass_night, grass_night2, grass_night, grass_night, grass_night2, [sign, grass_night], grass_night2, [tree, grass_night], grass_night2, [tree, grass_night], grass_night2, [tree, grass_night], grass_night2, grass_night2, grass_night2, [stone, grass_night], grass_night2, grass_night, grass_night, [junk_can, grass_night2], grass_night, grass_night2, [junk_can, grass_night], grass_night, [stone, grass_night2], grass_night, grass_night, [junk_can, grass_night], grass_night, grass_night2, grass_night, [stone, grass_night], grass_night, [junk_can, grass_night], grass_night, [sign, grass_night2], grass_night, grass_night ,grass_night, [junk_can, grass_night], grass_night, [junk_can, grass_night2], grass_night, grass_night],
         [[junk_can, grass_night], grass_night, grass_night2, grass_night2, grass_night, grass_night2, grass_night, [stone, grass_night], grass_night, grass_night, grass_night2, grass_night2, grass_night, [sign, grass_night], grass_night2, grass_night2, grass_night, [stone, grass_night], grass_night, grass_night, grass_night2, grass_night2, grass_night, grass_night2, grass_night, grass_night, grass_night2, [sign, grass_night], grass_night2, [tree, grass_night], grass_night2, [tree, grass_night], grass_night2, [tree, grass_night], grass_night2, grass_night2, grass_night2, [stone, grass_night], grass_night2, grass_night, grass_night, [junk_can, grass_night2], grass_night, grass_night2, [junk_can, grass_night], grass_night, [stone, grass_night2], grass_night, grass_night, [junk_can, grass_night], grass_night, [junk_can, grass_night2], grass_night, grass_night2, grass_night, [junk_can, grass_night], grass_night, sign, grass_night2, grass_night, grass_night ,grass_night, [junk_can, grass_night], grass_night, [junk_can, grass_night2], grass_night, grass_night],
         [grass_night, grass_night2, grass_night2, grass_night2, grass_night, grass_night2, grass_night, [stone, grass_night], grass_night, grass_night, grass_night2, grass_night2, grass_night, [sign, grass_night], grass_night2, grass_night2, grass_night, [stone, grass_night], grass_night, grass_night, grass_night2, grass_night2, grass_night, grass_night2, grass_night, grass_night, grass_night2, [sign, grass_night], grass_night2, [tree, grass_night], grass_night2, [tree, grass_night], grass_night2, [tree, grass_night], grass_night2, grass_night2, grass_night2, [stone, grass_night], grass_night2, grass_night, grass_night, [junk_can, grass_night2], grass_night, grass_night2, [stone, grass_night], grass_night, grass_night2, grass_night, [sign, grass_night], grass_night2, grass_night, grass_night2, grass_night, [stone, grass_night], grass_night, [junk_can, grass_night2], [stone, grass_night], grass_night, grass_night, [stone, grass_night] ,grass_night, grass_night, grass_night, grass_night2, grass_night, grass_night],
         [grass_night2, grass_night, grass_night2, grass_night2, grass_night, grass_night2, grass_night, [stone, grass_night], grass_night, grass_night, grass_night2, grass_night2, grass_night, [sign, grass_night], grass_night2, grass_night2, grass_night, [stone, grass_night], grass_night, grass_night, grass_night2, grass_night2, grass_night, grass_night2, grass_night, grass_night, grass_night2, [sign, grass_night], grass_night2, [tree, grass_night], grass_night2, [tree, grass_night], grass_night2, [tree, grass_night], grass_night2, grass_night2, grass_night2, [stone, grass_night], grass_night2, grass_night, grass_night, [junk_can, grass_night2], grass_night, grass_night2, [junk_can, grass_night], grass_night, [stone, grass_night2], grass_night, grass_night2, [junk_can, grass_night], grass_night, [junk_can, grass_night2], grass_night, grass_night, grass_night, [junk_can, grass_night], grass_night, [sign, grass_night2], grass_night, grass_night ,grass_night, [junk_can, grass_night], grass_night, [junk_can, grass_night2], grass_night, grass_night],
         [grass_night, grass_night, grass_night2, grass_night2, grass_night, grass_night2, grass_night2, [stone, grass_night], grass_night, grass_night, grass_night2, grass_night2, grass_night, [sign, grass_night], grass_night2, grass_night2, grass_night, [stone, grass_night], grass_night, grass_night, grass_night2, grass_night2, grass_night, grass_night2, grass_night, grass_night, grass_night2, [sign, grass_night], grass_night2, [tree, grass_night], grass_night2, [tree, grass_night], grass_night2, [tree, grass_night], grass_night2, grass_night2, grass_night2, [stone, grass_night], grass_night2, grass_night, grass_night, [junk_can, grass_night2], grass_night, grass_night2, [junk_can, grass_night], grass_night, [stone, grass_night2], grass_night, grass_night, [junk_can, grass_night], grass_night, [junk_can, grass_night2], grass_night, [stone, grass_night], grass_night, [junk_can, grass_night], grass_night, [sign, grass_night], grass_night, grass_night ,grass_night, [junk_can, grass_night], grass_night, [junk_can, grass_night2], grass_night, grass_night],
         [[stone, grass_night], grass_night, grass_night2, grass_night2, grass_night, [stone, grass_night], grass_night, [sign, grass_night], grass_night, grass_night2, grass_night2, [stone, grass_night], grass_night, [sign, grass_night], grass_night2, grass_night2, grass_night, grass_night2, grass_night, grass_night, grass_night2, grass_night2, grass_night, grass_night2, grass_night, grass_night, grass_night2, [sign, grass_night], grass_night2, [tree, grass_night], grass_night2, [tree, grass_night], grass_night2, [tree, grass_night], grass_night2, grass_night2, grass_night2, [stone, grass_night], grass_night2, grass_night, grass_night, [junk_can, grass_night2], grass_night, grass_night2, [junk_can, grass_night], grass_night2, [stone, grass_night2], grass_night, grass_night, [junk_can, grass_night], grass_night, grass_night2, grass_night2, grass_night, grass_night, [junk_can, grass_night], grass_night, [sign, grass_night2], grass_night, grass_night ,grass_night, [junk_can, grass_night], grass_night, [junk_can, grass_night2], grass_night, grass_night],
         [grass_night2, grass_night, grass_night2, grass_night2, grass_night, grass_night2, grass_night, [stone, grass_night], grass_night, grass_night, grass_night2, grass_night2, grass_night, [sign, grass_night], grass_night2, grass_night2, grass_night, [stone, grass_night], grass_night, grass_night, grass_night2, grass_night2, grass_night, grass_night2, grass_night, grass_night, grass_night2, [sign, grass_night], grass_night2, [tree, grass_night], grass_night2, [tree, grass_night], grass_night2, [tree, grass_night], grass_night2, grass_night2, grass_night2, [stone, grass_night], grass_night2, grass_night, grass_night, [junk_can, grass_night2], grass_night, grass_night2, [junk_can, grass_night], grass_night, [stone, grass_night2], grass_night, grass_night, [junk_can, grass_night], grass_night, grass_night2, grass_night, grass_night, grass_night, [junk_can, grass_night], grass_night, [sign, grass_night2], grass_night, grass_night ,grass_night, [junk_can, grass_night], grass_night, [junk_can, grass_night2], grass_night, grass_night],
         [grass_night, grass_night2, grass_night2, grass_night, grass_night, grass_night2, grass_night, [stone, grass_night], grass_night, grass_night, grass_night2, grass_night2, grass_night, [sign, grass_night], grass_night2, grass_night2, grass_night, [stone, grass_night], grass_night, grass_night, grass_night2, grass_night2, grass_night, grass_night2, grass_night, grass_night, grass_night2, [sign, grass_night], grass_night2, [tree, grass_night], grass_night2, [tree, grass_night], grass_night2, [tree, grass_night], grass_night2, grass_night2, grass_night2, [stone, grass_night], grass_night2, grass_night, grass_night, [junk_can, grass_night2], grass_night, grass_night2, [junk_can, grass_night], grass_night, [stone, grass_night2], grass_night, grass_night2, [junk_can, grass_night], grass_night2, [junk_can, grass_night], grass_night2, grass_night, grass_night, [junk_can, grass_night], grass_night, [sign, grass_night], grass_night, grass_night ,grass_night, [junk_can, grass_night], grass_night, [junk_can, grass_night2], grass_night, grass_night],
         [grass_night2, grass_night, grass_night2, grass_night2, grass_night, grass_night2, grass_night, [stone, grass_night], grass_night, grass_night, grass_night2, grass_night2, grass_night, [sign, grass_night], grass_night2, grass_night2, grass_night, [stone, grass_night], grass_night, grass_night, grass_night2, grass_night2, grass_night, grass_night2, grass_night, grass_night, grass_night2, [sign, grass_night], grass_night2, [tree, grass_night], grass_night2, [tree, grass_night], grass_night2, [tree, grass_night], grass_night2, grass_night2, grass_night2, [stone, grass_night], grass_night2, grass_night, grass_night, [junk_can, grass_night2], grass_night, grass_night2, [junk_can, grass_night], grass_night2, [stone, grass_night2], grass_night, grass_night, [junk_can, grass_night], grass_night, [junk_can, grass_night2], grass_night, grass_night, grass_night, [junk_can, grass_night], grass_night, [sign, grass_night2], grass_night, grass_night ,grass_night, [junk_can, grass_night], grass_night, [junk_can, grass_night2], grass_night, grass_night]
         ]
