import pygame


class StartLocation:
    def __init__(self):
        self.g = pygame.image.load("data/grass_night.png").convert_alpha()
        self.j = pygame.image.load("data/junk_can.png").convert_alpha()
        self.tree = pygame.image.load("data/tree.png").convert_alpha()
        self.s = pygame.image.load('data/stone.png').convert_alpha()
        self.g2 = pygame.image.load("data/grass_night2.png").convert_alpha()
        self.sign = pygame.image.load('data/Signs.png').convert_alpha()
        self.pol = [self.g, self.g2]
        self.barriers = [self.tree, self.j, self.s, self.sign]
        self.width_of_base = {self.tree: 7 * 4, self.j: 3 * 4, self.s: 11 * 4, self.sign: 6 * 4}
        self.location = [
            [[self.j, self.g2], [self.s, self.g2], self.g, self.g2, [self.s, self.g], self.g2, self.g, self.g2, self.g2,
             [self.sign, self.g], [self.j, self.g2], self.g, [self.s, self.g2], self.g2, [self.s, self.g], self.g,
             self.g, self.g2, self.g2, self.g, [self.s, self.g], self.g2, self.g, [self.sign, self.g2], self.g, self.g2,
             self.g, self.g2, self.g, self.g, self.g, self.g2, [self.j, self.g], self.g, [self.j, self.g2], self.g,
             self.g, [self.j, self.g], self.g, [self.s, self.g], self.g2, self.g, [self.s, self.g], self.g,
             [self.j, self.g2], self.g, self.g, self.g2],
            [self.g2, self.g, self.g2, self.g2, self.g, self.g2, self.g, [self.s, self.g], self.g, self.g, self.g2,
             self.g2, self.g, [self.sign, self.g], self.g2, self.g2, self.g, [self.s, self.g], self.g, self.g, self.g2,
             self.g2, self.g, self.g2, self.g, self.g, self.g2, [self.sign, self.g], self.g2, [self.tree, self.g],
             self.g2, [self.tree, self.g], self.g2, [self.tree, self.g], self.g2, self.g2, self.g2, [self.s, self.g],
             self.g2, self.g, self.g, [self.j, self.g2], self.g, self.g2, [self.j, self.g], self.g, [self.s, self.g2],
             self.g, self.g, [self.j, self.g], self.g, [self.j, self.g], self.g, self.g, self.g, [self.j, self.g],
             self.g, [self.sign, self.g2], self.g, self.g, self.g, [self.j, self.g], self.g, [self.j, self.g2], self.g,
             self.g],
            [[self.s, self.g], self.g2, self.g2, [self.s, self.g], self.g, self.g2, self.g, self.g2, self.g2,
             [self.sign, self.g], self.g2, self.g2, self.g, [self.sign, self.g], self.g, self.g2, self.g2, self.g,
             self.g2, self.g2, [self.s, self.g], self.g, self.g2, self.g, self.g, self.g2, self.g, self.g2, self.g2,
             self.g2, self.g2, self.g, [self.s, self.g], self.g2, [self.s, self.g], self.g, self.g2, self.g, self.g,
             [self.j, self.g2], self.g, self.g2, [self.j, self.g], self.g, [self.s, self.g2], self.g, self.g,
             [self.j, self.g], self.g, [self.j, self.g2], self.g, self.g, self.g, [self.j, self.g], self.g,
             [self.sign, self.g2], self.g, self.g, self.g, [self.j, self.g], self.g, [self.j, self.g2], self.g, self.g],
            [self.g, self.g2, self.g2, self.g2, self.g, self.g2, self.g, [self.s, self.g], self.g, self.g, self.g2,
             self.g2, self.g, [self.sign, self.g], self.g2, self.g2, self.g, [self.s, self.g], self.g, self.g, self.g2,
             [self.tree, self.g2], self.g, self.g2, self.g, self.g, self.g2, [self.sign, self.g], self.g2,
             [self.tree, self.g], self.g2, [self.tree, self.g], self.g2, [self.tree, self.g], self.g2, self.g2, self.g2,
             [self.s, self.g], self.g2, self.g, self.g, [self.j, self.g2], self.g, self.g2, [self.j, self.g], self.g,
             [self.s, self.g2], self.g, self.g, [self.j, self.g], self.g, [self.j, self.g2], self.g, self.g, self.g,
             [self.j, self.g], self.g, [self.sign, self.g], self.g, self.g, self.g, [self.j, self.g], self.g,
             [self.j, self.g2], self.g, self.g],
            [[self.s, self.g], self.g, self.g2, self.g2, self.g, self.g2, self.g, [self.s, self.g], self.g, self.g,
             self.g2, self.g2, self.g, [self.sign, self.g], self.g2, self.g2, self.g, [self.s, self.g], self.g, self.g,
             self.g2, self.g2, self.g, self.g2, self.g, self.g, self.g2, [self.sign, self.g], self.g2,
             [self.tree, self.g], self.g2, [self.tree, self.g], self.g2, [self.tree, self.g], self.g2, self.g2, self.g2,
             [self.s, self.g], self.g2, self.g, self.g, [self.j, self.g2], self.g, self.g2, [self.j, self.g], self.g,
             [self.s, self.g2], self.g, self.g, [self.j, self.g], self.g, [self.j, self.g2], self.g, self.g, self.g,
             self.g, self.g, self.g2, self.g, self.g, self.g, self.g2, self.g, self.g, self.g, self.g],
            [self.g, self.g2, self.g, self.g2, self.g2, self.g2, self.g, self.g, self.g, self.g, self.g2, self.g2,
             self.g, self.g2, self.g2, self.g2, self.g2, self.g2, self.g, self.g2, self.g2, self.g2, self.g, self.g2,
             self.g, self.g2, self.g2, self.g, self.g2, self.g2, self.g2, self.g, self.g2, self.g2, self.g2, self.g2,
             self.g, self.g2, self.g2, self.g, self.g, self.g2, self.g, self.g2, self.g, self.g, self.g, self.g,
             self.g2, self.g2, self.g, self.g, self.g, self.g, self.g, self.g2, self.g, self.g2, self.g, self.g, self.g,
             self.g, self.g, self.g, self.g, self.g],
            [self.g, self.g2, self.g, self.g2, self.g2, self.g2, self.g, self.g, self.g, self.g, self.g2, self.g2,
             self.g, self.g2, self.g2, self.g2, self.g2, self.g2, self.g, self.g2, self.g2, self.g2, self.g, self.g2,
             self.g, self.g2, self.g2, self.g, self.g2, self.g2, self.g2, self.g, self.g2, self.g2, self.g2, self.g2,
             self.g, self.g2, self.g2, self.g, self.g, self.g2, self.g, self.g2, self.g, self.g, self.g, self.g,
             self.g2, self.g2, self.g, self.g, self.g, self.g, self.g, self.g2, self.g, self.g2, self.g, self.g, self.g,
             self.g, self.g, self.g, self.g, self.g],
            [[self.s, self.g], self.g, self.g2, self.g2, self.g, self.g2, self.g, [self.s, self.g], self.g, self.g,
             self.g2, self.g2, self.g, [self.sign, self.g], self.g2, self.g2, self.g, [self.s, self.g], self.g, self.g,
             self.g2, self.g2, self.g, self.g2, self.g, self.g, self.g2, [self.sign, self.g], self.g2,
             [self.tree, self.g], self.g2, [self.tree, self.g], self.g2, [self.tree, self.g], self.g2, self.g2, self.g2,
             [self.s, self.g], self.g2, self.g, self.g, [self.j, self.g2], self.g, self.g2, [self.s, self.g], self.g2,
             [self.s, self.g2], self.g, self.g, [self.j, self.g], [self.sign, self.g], [self.j, self.g2], self.g,
             self.g, self.g, [self.j, self.g], self.g, [self.sign, self.g], self.g, self.g, self.g, [self.j, self.g],
             self.g, [self.j, self.g2], self.g, self.g],
            [self.g, self.g, self.g2, self.g2, self.g, self.g2, self.g, [self.s, self.g], self.g, self.g, self.g2,
             self.g2, self.g, [self.sign, self.g], self.g2, self.g2, self.g, [self.s, self.g], self.g, self.g, self.g2,
             self.g2, self.g, self.g2, self.g, self.g, self.g2, [self.sign, self.g], self.g2, [self.tree, self.g],
             self.g2, [self.tree, self.g], self.g2, [self.tree, self.g], self.g2, self.g2, self.g2, [self.s, self.g],
             self.g2, self.g, self.g, [self.j, self.g2], self.g, self.g2, self.g, self.g, [self.s, self.g2], self.g,
             self.g, [self.j, self.g], self.g, self.g2, self.g2, self.g, self.g, [self.j, self.g], self.g,
             [self.sign, self.g], self.g, self.g, self.g, [self.j, self.g], self.g, [self.j, self.g2], self.g, self.g],
            [[self.sign, self.g], self.g, self.g2, self.g2, self.g, self.g2, self.g, [self.s, self.g], self.g, self.g,
             self.g2, self.g2, self.g, [self.sign, self.g], self.g2, self.g2, self.g, [self.s, self.g], self.g, self.g,
             self.g2, self.g2, self.g, self.g2, self.g, self.g, self.g2, [self.sign, self.g], self.g2,
             [self.tree, self.g], self.g2, [self.tree, self.g], self.g2, [self.tree, self.g], self.g2, self.g2, self.g2,
             [self.s, self.g], self.g2, self.g, self.g, [self.j, self.g2], self.g, self.g2, self.g, self.g,
             [self.s, self.g2], self.g, self.g, [self.j, self.g], self.g, self.g2, self.g, self.g, self.g,
             [self.j, self.g], self.g, [self.sign, self.g], self.g, self.g, self.g, [self.j, self.g], self.g,
             [self.j, self.g2], self.g, self.g],
            [self.g, self.g, self.g2, self.g2, self.g, self.g2, self.g, [self.s, self.g], self.g, self.g, self.g2,
             self.g2, self.g, [self.sign, self.g], self.g2, self.g2, self.g, [self.s, self.g], self.g, self.g, self.g2,
             self.g2, self.g, self.g2, self.g, self.g, self.g2, [self.sign, self.g], self.g2, [self.tree, self.g],
             self.g2, [self.tree, self.g], self.g2, [self.tree, self.g], self.g2, self.g2, self.g2, [self.s, self.g],
             self.g2, self.g, self.g, [self.j, self.g2], self.g, self.g2, [self.j, self.g], self.g, [self.s, self.g2],
             self.g, self.g, [self.j, self.g], self.g, self.g2, self.g, [self.s, self.g], self.g, [self.j, self.g],
             self.g, [self.sign, self.g2], self.g, self.g, self.g, [self.j, self.g], self.g, [self.j, self.g2], self.g,
             self.g],
            [[self.j, self.g], self.g, self.g2, self.g2, self.g, self.g2, self.g, [self.s, self.g], self.g, self.g,
             self.g2, self.g2, self.g, [self.sign, self.g], self.g2, self.g2, self.g, [self.s, self.g], self.g, self.g,
             self.g2, self.g2, self.g, self.g2, self.g, self.g, self.g2, [self.sign, self.g], self.g2,
             [self.tree, self.g], self.g2, [self.tree, self.g], self.g2, [self.tree, self.g], self.g2, self.g2, self.g2,
             [self.s, self.g], self.g2, self.g, self.g, [self.j, self.g2], self.g, self.g2, [self.j, self.g], self.g,
             [self.s, self.g2], self.g, self.g, [self.j, self.g], self.g, [self.j, self.g2], self.g, self.g2, self.g,
             [self.j, self.g], self.g, self.sign, self.g2, self.g, self.g, self.g, [self.j, self.g], self.g,
             [self.j, self.g2], self.g, self.g],
            [self.g, self.g2, self.g2, self.g2, self.g, self.g2, self.g, [self.s, self.g], self.g, self.g, self.g2,
             self.g2, self.g, [self.sign, self.g], self.g2, self.g2, self.g, [self.s, self.g], self.g, self.g, self.g2,
             self.g2, self.g, self.g2, self.g, self.g, self.g2, [self.sign, self.g], self.g2, [self.tree, self.g],
             self.g2, [self.tree, self.g], self.g2, [self.tree, self.g], self.g2, self.g2, self.g2, [self.s, self.g],
             self.g2, self.g, self.g, [self.j, self.g2], self.g, self.g2, [self.s, self.g], self.g, self.g2, self.g,
             [self.sign, self.g], self.g2, self.g, self.g2, self.g, [self.s, self.g], self.g, [self.j, self.g2],
             [self.s, self.g], self.g, self.g, [self.s, self.g], self.g, self.g, self.g, self.g2, self.g, self.g],
            [self.g2, self.g, self.g2, self.g2, self.g, self.g2, self.g, [self.s, self.g], self.g, self.g, self.g2,
             self.g2, self.g, [self.sign, self.g], self.g2, self.g2, self.g, [self.s, self.g], self.g, self.g, self.g2,
             self.g2, self.g, self.g2, self.g, self.g, self.g2, [self.sign, self.g], self.g2, [self.tree, self.g],
             self.g2, [self.tree, self.g], self.g2, [self.tree, self.g], self.g2, self.g2, self.g2, [self.s, self.g],
             self.g2, self.g, self.g, [self.j, self.g2], self.g, self.g2, [self.j, self.g], self.g, [self.s, self.g2],
             self.g, self.g2, [self.j, self.g], self.g, [self.j, self.g2], self.g, self.g, self.g, [self.j, self.g],
             self.g, [self.sign, self.g2], self.g, self.g, self.g, [self.j, self.g], self.g, [self.j, self.g2], self.g,
             self.g],
            [self.g, self.g, self.g2, self.g2, self.g, self.g2, self.g2, [self.s, self.g], self.g, self.g, self.g2,
             self.g2, self.g, [self.sign, self.g], self.g2, self.g2, self.g, [self.s, self.g], self.g, self.g, self.g2,
             self.g2, self.g, self.g2, self.g, self.g, self.g2, [self.sign, self.g], self.g2, [self.tree, self.g],
             self.g2, [self.tree, self.g], self.g2, [self.tree, self.g], self.g2, self.g2, self.g2, [self.s, self.g],
             self.g2, self.g, self.g, [self.j, self.g2], self.g, self.g2, [self.j, self.g], self.g, [self.s, self.g2],
             self.g, self.g, [self.j, self.g], self.g, [self.j, self.g2], self.g, [self.s, self.g], self.g,
             [self.j, self.g], self.g, [self.sign, self.g], self.g, self.g, self.g, [self.j, self.g], self.g,
             [self.j, self.g2], self.g, self.g],
            [[self.s, self.g], self.g, self.g2, self.g2, self.g, [self.s, self.g], self.g, [self.sign, self.g], self.g,
             self.g2, self.g2, [self.s, self.g], self.g, [self.sign, self.g], self.g2, self.g2, self.g, self.g2, self.g,
             self.g, self.g2, self.g2, self.g, self.g2, self.g, self.g, self.g2, [self.sign, self.g], self.g2,
             [self.tree, self.g], self.g2, [self.tree, self.g], self.g2, [self.tree, self.g], self.g2, self.g2, self.g2,
             [self.s, self.g], self.g2, self.g, self.g, [self.j, self.g2], self.g, self.g2, [self.j, self.g], self.g2,
             [self.s, self.g2], self.g, self.g, [self.j, self.g], self.g, self.g2, self.g2, self.g, self.g,
             [self.j, self.g], self.g, [self.sign, self.g2], self.g, self.g, self.g, [self.j, self.g], self.g,
             [self.j, self.g2], self.g, self.g],
            [self.g2, self.g, self.g2, self.g2, self.g, self.g2, self.g, [self.s, self.g], self.g, self.g, self.g2,
             self.g2, self.g, [self.sign, self.g], self.g2, self.g2, self.g, [self.s, self.g], self.g, self.g, self.g2,
             self.g2, self.g, self.g2, self.g, self.g, self.g2, [self.sign, self.g], self.g2, [self.tree, self.g],
             self.g2, [self.tree, self.g], self.g2, [self.tree, self.g], self.g2, self.g2, self.g2, [self.s, self.g],
             self.g2, self.g, self.g, [self.j, self.g2], self.g, self.g2, [self.j, self.g], self.g, [self.s, self.g2],
             self.g, self.g, [self.j, self.g], self.g, self.g2, self.g, self.g, self.g, [self.j, self.g], self.g,
             [self.sign, self.g2], self.g, self.g, self.g, [self.j, self.g], self.g, [self.j, self.g2], self.g, self.g],
            [self.g, self.g2, self.g2, self.g, self.g, self.g2, self.g, [self.s, self.g], self.g, self.g, self.g2,
             self.g2, self.g, [self.sign, self.g], self.g2, self.g2, self.g, [self.s, self.g], self.g, self.g, self.g2,
             self.g2, self.g, self.g2, self.g, self.g, self.g2, [self.sign, self.g], self.g2, [self.tree, self.g],
             self.g2, [self.tree, self.g], self.g2, [self.tree, self.g], self.g2, self.g2, self.g2, [self.s, self.g],
             self.g2, self.g, self.g, [self.j, self.g2], self.g, self.g2, [self.j, self.g], self.g, [self.s, self.g2],
             self.g, self.g2, [self.j, self.g], self.g2, [self.j, self.g], self.g2, self.g, self.g, [self.j, self.g],
             self.g, [self.sign, self.g], self.g, self.g, self.g, [self.j, self.g], self.g, [self.j, self.g2], self.g,
             self.g],
            [self.g2, self.g, self.g2, self.g2, self.g, self.g2, self.g, [self.s, self.g], self.g, self.g, self.g2,
             self.g2, self.g, [self.sign, self.g], self.g2, self.g2, self.g, [self.s, self.g], self.g, self.g, self.g2,
             self.g2, self.g, self.g2, self.g, self.g, self.g2, [self.sign, self.g], self.g2, [self.tree, self.g],
             self.g2, [self.tree, self.g], self.g2, [self.tree, self.g], self.g2, self.g2, self.g2, [self.s, self.g],
             self.g2, self.g, self.g, [self.j, self.g2], self.g, self.g2, [self.j, self.g], self.g2, [self.s, self.g2],
             self.g, self.g, [self.j, self.g], self.g, [self.j, self.g2], self.g, self.g, self.g, [self.j, self.g],
             self.g, [self.sign, self.g2], self.g, self.g, self.g, [self.j, self.g], self.g, [self.j, self.g2], self.g,
             self.g],
            [self.g2, self.g, self.g2, self.g2, self.g, self.g2, self.g, [self.s, self.g], self.g, self.g, self.g2,
             self.g2, self.g, [self.sign, self.g], self.g2, self.g2, self.g, [self.s, self.g], self.g, self.g, self.g2,
             self.g2, self.g, self.g2, self.g, self.g, self.g2, [self.sign, self.g], self.g2, [self.tree, self.g],
             self.g2, [self.tree, self.g], self.g2, [self.tree, self.g], self.g2, self.g2, self.g2, [self.s, self.g],
             self.g2, self.g, self.g, [self.j, self.g2], self.g, self.g2, [self.j, self.g], self.g, [self.s, self.g2],
             self.g, self.g, [self.j, self.g], self.g, [self.j, self.g], self.g, self.g, self.g, [self.j, self.g],
             self.g, [self.sign, self.g2], self.g, self.g, self.g, [self.j, self.g], self.g, [self.j, self.g2], self.g,
             self.g],
            [[self.s, self.g], self.g2, self.g2, [self.s, self.g], self.g, self.g2, self.g, self.g2, self.g2,
             [self.sign, self.g], self.g2, self.g2, self.g, [self.sign, self.g], self.g, self.g2, self.g2, self.g,
             self.g2, self.g2, [self.s, self.g], self.g, self.g2, self.g, self.g, self.g2, self.g, self.g2, self.g2,
             self.g2, self.g2, self.g, [self.s, self.g], self.g2, [self.s, self.g], self.g, self.g2, self.g, self.g,
             [self.j, self.g2], self.g, self.g2, [self.j, self.g], self.g, [self.s, self.g2], self.g, self.g,
             [self.j, self.g], self.g, [self.j, self.g2], self.g, self.g, self.g, [self.j, self.g], self.g,
             [self.sign, self.g2], self.g, self.g, self.g, [self.j, self.g], self.g, [self.j, self.g2], self.g, self.g],
            [self.g, self.g2, self.g2, self.g2, self.g, self.g2, self.g, [self.s, self.g], self.g, self.g, self.g2,
             self.g2, self.g, [self.sign, self.g], self.g2, self.g2, self.g, [self.s, self.g], self.g, self.g, self.g2,
             self.g2, self.g, self.g2, self.g, self.g, self.g2, [self.sign, self.g], self.g2, [self.tree, self.g],
             self.g2, [self.tree, self.g], self.g2, [self.tree, self.g], self.g2, self.g2, self.g2, [self.s, self.g],
             self.g2, self.g, self.g, [self.j, self.g2], self.g, self.g2, [self.j, self.g], self.g, [self.s, self.g2],
             self.g, self.g, [self.j, self.g], self.g, [self.j, self.g2], self.g, self.g, self.g, [self.j, self.g],
             self.g, [self.sign, self.g], self.g, self.g, self.g, [self.j, self.g], self.g, [self.j, self.g2], self.g,
             self.g],
            [[self.s, self.g], self.g, self.g2, self.g2, self.g, self.g2, self.g, [self.s, self.g], self.g, self.g,
             self.g2, self.g2, self.g, [self.sign, self.g], self.g2, self.g2, self.g, [self.s, self.g], self.g, self.g,
             self.g2, self.g2, self.g, self.g2, self.g, self.g, self.g2, [self.sign, self.g], self.g2,
             [self.tree, self.g], self.g2, [self.tree, self.g], self.g2, [self.tree, self.g], self.g2, self.g2, self.g2,
             [self.s, self.g], self.g2, self.g, self.g, [self.j, self.g2], self.g, self.g2, [self.j, self.g], self.g,
             [self.s, self.g2], self.g, self.g, [self.j, self.g], self.g, [self.j, self.g2], self.g, self.g, self.g,
             self.g, self.g, self.g2, self.g, self.g, self.g, self.g2, self.g, self.g, self.g, self.g],
            [self.g, self.g2, self.g, self.g2, self.g2, self.g2, self.g, self.g, self.g, self.g, self.g2, self.g2,
             self.g, self.g2, self.g2, self.g2, self.g2, self.g2, self.g, self.g2, self.g2, self.g2, self.g, self.g2,
             self.g, self.g2, self.g2, self.g, self.g2, self.g2, self.g2, self.g, self.g2, self.g2, self.g2, self.g2,
             self.g, self.g2, self.g2, self.g, self.g, self.g2, self.g, self.g2, self.g, self.g, self.g, self.g,
             self.g2, self.g2, self.g, self.g, self.g, self.g, self.g, self.g2, self.g, self.g2, self.g, self.g, self.g,
             self.g, self.g, self.g, self.g, self.g],
            [self.g, self.g2, self.g, self.g2, self.g2, self.g2, self.g, self.g, self.g, self.g, self.g2, self.g2,
             self.g, self.g2, self.g2, self.g2, self.g2, self.g2, self.g, self.g2, self.g2, self.g2, self.g, self.g2,
             self.g, self.g2, self.g2, self.g, self.g2, self.g2, self.g2, self.g, self.g2, self.g2, self.g2, self.g2,
             self.g, self.g2, self.g2, self.g, self.g, self.g2, self.g, self.g2, self.g, self.g, self.g, self.g,
             self.g2, self.g2, self.g, self.g, self.g, self.g, self.g, self.g2, self.g, self.g2, self.g, self.g, self.g,
             self.g, self.g, self.g, self.g, self.g],
            [[self.s, self.g], self.g, self.g2, self.g2, self.g, self.g2, self.g, [self.s, self.g], self.g, self.g,
             self.g2, self.g2, self.g, [self.sign, self.g], self.g2, self.g2, self.g, [self.s, self.g], self.g, self.g,
             self.g2, self.g2, self.g, self.g2, self.g, self.g, self.g2, [self.sign, self.g], self.g2,
             [self.tree, self.g], self.g2, [self.tree, self.g], self.g2, [self.tree, self.g], self.g2, self.g2, self.g2,
             [self.s, self.g], self.g2, self.g, self.g, [self.j, self.g2], self.g, self.g2, [self.s, self.g], self.g2,
             [self.s, self.g2], self.g, self.g, [self.j, self.g], [self.sign, self.g], [self.j, self.g2], self.g,
             self.g, self.g, [self.j, self.g], self.g, [self.sign, self.g], self.g, self.g, self.g, [self.j, self.g],
             self.g, [self.j, self.g2], self.g, self.g],
            [self.g, self.g, self.g2, self.g2, self.g, self.g2, self.g, [self.s, self.g], self.g, self.g, self.g2,
             self.g2, self.g, [self.sign, self.g], self.g2, self.g2, self.g, [self.s, self.g], self.g, self.g, self.g2,
             self.g2, self.g, self.g2, self.g, self.g, self.g2, [self.sign, self.g], self.g2, [self.tree, self.g],
             self.g2, [self.tree, self.g], self.g2, [self.tree, self.g], self.g2, self.g2, self.g2, [self.s, self.g],
             self.g2, self.g, self.g, [self.j, self.g2], self.g, self.g2, self.g, self.g, [self.s, self.g2], self.g,
             self.g, [self.j, self.g], self.g, self.g2, self.g2, self.g, self.g, [self.j, self.g], self.g,
             [self.sign, self.g], self.g, self.g, self.g, [self.j, self.g], self.g, [self.j, self.g2], self.g, self.g],
            [[self.sign, self.g], self.g, self.g2, self.g2, self.g, self.g2, self.g, [self.s, self.g], self.g, self.g,
             self.g2, self.g2, self.g, [self.sign, self.g], self.g2, self.g2, self.g, [self.s, self.g], self.g, self.g,
             self.g2, self.g2, self.g, self.g2, self.g, self.g, self.g2, [self.sign, self.g], self.g2,
             [self.tree, self.g], self.g2, [self.tree, self.g], self.g2, [self.tree, self.g], self.g2, self.g2, self.g2,
             [self.s, self.g], self.g2, self.g, self.g, [self.j, self.g2], self.g, self.g2, self.g, self.g,
             [self.s, self.g2], self.g, self.g, [self.j, self.g], self.g, self.g2, self.g, self.g, self.g,
             [self.j, self.g], self.g, [self.sign, self.g], self.g, self.g, self.g, [self.j, self.g], self.g,
             [self.j, self.g2], self.g, self.g],
            [self.g, self.g, self.g2, self.g2, self.g, self.g2, self.g, [self.s, self.g], self.g, self.g, self.g2,
             self.g2, self.g, [self.sign, self.g], self.g2, self.g2, self.g, [self.s, self.g], self.g, self.g, self.g2,
             self.g2, self.g, self.g2, self.g, self.g, self.g2, [self.sign, self.g], self.g2, [self.tree, self.g],
             self.g2, [self.tree, self.g], self.g2, [self.tree, self.g], self.g2, self.g2, self.g2, [self.s, self.g],
             self.g2, self.g, self.g, [self.j, self.g2], self.g, self.g2, [self.j, self.g], self.g, [self.s, self.g2],
             self.g, self.g, [self.j, self.g], self.g, self.g2, self.g, [self.s, self.g], self.g, [self.j, self.g],
             self.g, [self.sign, self.g2], self.g, self.g, self.g, [self.j, self.g], self.g, [self.j, self.g2], self.g,
             self.g],
            [[self.j, self.g], self.g, self.g2, self.g2, self.g, self.g2, self.g, [self.s, self.g], self.g, self.g,
             self.g2, self.g2, self.g, [self.sign, self.g], self.g2, self.g2, self.g, [self.s, self.g], self.g, self.g,
             self.g2, self.g2, self.g, self.g2, self.g, self.g, self.g2, [self.sign, self.g], self.g2,
             [self.tree, self.g], self.g2, [self.tree, self.g], self.g2, [self.tree, self.g], self.g2, self.g2, self.g2,
             [self.s, self.g], self.g2, self.g, self.g, [self.j, self.g2], self.g, self.g2, [self.j, self.g], self.g,
             [self.s, self.g2], self.g, self.g, [self.j, self.g], self.g, [self.j, self.g2], self.g, self.g2, self.g,
             [self.j, self.g], self.g, self.sign, self.g2, self.g, self.g, self.g, [self.j, self.g], self.g,
             [self.j, self.g2], self.g, self.g]]

